// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjkOU09xh18bkaHVQvNJlokLcns1y0qlA',
    appId: '1:63099873423:web:d756cf52ecb4505b3768fa',
    messagingSenderId: '63099873423',
    projectId: 'drinkdiary-ac138',
    authDomain: 'drinkdiary-ac138.firebaseapp.com',
    storageBucket: 'drinkdiary-ac138.firebasestorage.app',
    measurementId: 'G-9XWT0JMWZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMWa1s-MWiJy7roEUWukb2iEpe4l2MrWc',
    appId: '1:63099873423:android:afc634624ee7499e3768fa',
    messagingSenderId: '63099873423',
    projectId: 'drinkdiary-ac138',
    storageBucket: 'drinkdiary-ac138.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQVnrVKz7yu7BqYKY91jK-nMK_-Ddqq00',
    appId: '1:63099873423:ios:a72604e0ede8b0d93768fa',
    messagingSenderId: '63099873423',
    projectId: 'drinkdiary-ac138',
    storageBucket: 'drinkdiary-ac138.firebasestorage.app',
    iosBundleId: 'com.example.drinkDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQVnrVKz7yu7BqYKY91jK-nMK_-Ddqq00',
    appId: '1:63099873423:ios:a72604e0ede8b0d93768fa',
    messagingSenderId: '63099873423',
    projectId: 'drinkdiary-ac138',
    storageBucket: 'drinkdiary-ac138.firebasestorage.app',
    iosBundleId: 'com.example.drinkDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjkOU09xh18bkaHVQvNJlokLcns1y0qlA',
    appId: '1:63099873423:web:2788805f9b7a7e8f3768fa',
    messagingSenderId: '63099873423',
    projectId: 'drinkdiary-ac138',
    authDomain: 'drinkdiary-ac138.firebaseapp.com',
    storageBucket: 'drinkdiary-ac138.firebasestorage.app',
    measurementId: 'G-KVC2S6CGTC',
  );
}
